import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import fs from "node:fs/promises";

import { createFileProjectStore } from "../src/projectStore.js";
import { handleApiRequest } from "../src/api.js";

test("CRUD de projects + export/sql (file store)", async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "diagram-db-"));
  const filename = path.join(dir, "projects.json");
  const store = createFileProjectStore({ filename });

  const createRes = await handleApiRequest({
    store,
    method: "POST",
    url: "/projects",
    body: { name: "My Diagram", diagram: { nodes: [], edges: [], databaseConfig: { enums: [] } } }
  });
  assert.equal(createRes.status, 201);
  assert.ok(createRes.json?.project?.id);

  const listRes = await handleApiRequest({ store, method: "GET", url: "/projects" });
  assert.equal(listRes.status, 200);
  assert.equal(listRes.json.projects.length, 1);

  const sqlRes = await handleApiRequest({
    store,
    method: "POST",
    url: `/projects/${createRes.json.project.id}/export/sql`
  });
  assert.equal(sqlRes.status, 200);
  assert.match(sqlRes.json.sql, /-- Generated by diagram-db/);
});

test("rotas compat /save e /load/:id", async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "diagram-db-"));
  const filename = path.join(dir, "projects.json");
  const store = createFileProjectStore({ filename });

  const saveRes = await handleApiRequest({
    store,
    method: "POST",
    url: "/save",
    body: { name: "Compat", nodes: [], edges: [], databaseConfig: { enums: [] } }
  });
  assert.equal(saveRes.status, 201);
  assert.ok(saveRes.json?.project?.id);

  const loadRes = await handleApiRequest({
    store,
    method: "GET",
    url: `/load/${saveRes.json.project.id}`
  });
  assert.equal(loadRes.status, 200);
  assert.equal(loadRes.json.project.id, saveRes.json.project.id);
});

